jira:
  license: "REPLACE_WITH_DEV_LICENSE"
  replicaCount: 1

  image:
    repository: atlassian/jira-software
    tag: 8.22.1

  service:
    type: ClusterIP
    port: 8080

  database:
    type: postgres
    host: postgres.dev.svc.cluster.local
    port: 5432
    name: jira_dev
    username: devuser
    password: devpass

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "nginx"
    hosts:
      - host: jira-dev.localtest.me
        paths:
          - path: /
            pathType: Prefix
    tls: []  # No TLS needed in dev

  resources:
    limits:
      cpu: "300m"
      memory: "512Mi"
    requests:
      cpu: "100m"
      memory: "256Mi"

  persistence:
    enabled: true
    size: 1Gi
    storageClass: standard

  nodeSelector: {}

  tolerations: []

  affinity: {}
